# Generated by Django 5.1.5 on 2025-04-14 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True)),
                ('save_message', models.BooleanField(default=True)),
                ('room_name', models.CharField(max_length=200)),
                ('current_pwd', models.TextField()),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_room_str', models.CharField(max_length=200)),
                ('user_ip', models.CharField(default='unknown', max_length=200)),
                ('msg_uuid', models.CharField(max_length=50)),
                ('user_uuid', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(default='')),
                ('message_with_scores', models.TextField(default='')),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chatmain.chatroom', verbose_name='the related poll')),
            ],
        ),
    ]
