# Generated by Django 5.1.5 on 2025-04-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatmain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='user_rated_score',
            field=models.CharField(default='-1', max_length=5),
        ),
    ]
