# Generated by Django 5.1.5 on 2025-04-30 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatmain', '0002_chatmessage_user_rated_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.CharField(default='unknown', max_length=200)),
                ('user_uuid', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='chatroom',
            name='bias_tendency',
            field=models.CharField(default='Please be neutral.', max_length=200),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='experiment_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='user_tendency',
            field=models.CharField(default='Please pick a topic that you would describe positively.', max_length=200),
        ),
        migrations.CreateModel(
            name='OneExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('experiment_progress', models.CharField(default='', max_length=200)),
                ('experiment_type', models.CharField(default='', max_length=200)),
                ('experiment_finished', models.BooleanField(default=False)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chatmain.anonymousparticipant')),
            ],
        ),
        migrations.AddField(
            model_name='chatroom',
            name='related_experiment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chatmain.oneexperiment'),
        ),
    ]
