# Generated by Django 5.1.5 on 2025-05-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatmain', '0005_remove_chatroom_experiment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='notes',
            field=models.TextField(default='-'),
        ),
    ]
