# Generated by Django 5.1.5 on 2025-05-27 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatmain', '0006_chatroom_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='chat_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chatmain.chatroom', verbose_name='the related room'),
        ),
        migrations.CreateModel(
            name='EventLogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='{}')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chatmain.chatroom', verbose_name='the related room')),
            ],
        ),
    ]
